services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: zouhir
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  zouhir-inventory-service:
    build: ./inventory-service
    container_name: zouhir-inventory-service
    ports:
      - '8081:8092'
    expose:
      - '8081'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
  customer-front-thymleaf:
    build: ./customer-front-thymleaf
    container_name: customer-front-thymleaf
    ports:
      - '8090:8090'
    expose:
      - '8090'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - KEYCLOAK_REDIRECT_URI= http://localhost:8090/login/oauth2/code/customer-client
      - KEYCLOAK_ISSUER_URI= http://localhost:8080/realms/customers-realm
volumes:
  mysql_data: